services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build: ./loan-api
    container_name: loan-api
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - LOAN_SUBMITTED_STREAM=${LOAN_SUBMITTED_STREAM:-loan_submitted}
      - LOAN_STATUS_STREAM=${LOAN_STATUS_STREAM:-loan_status}

  approver:
    build: ./approver
    container_name: approver
    ports:
      - "8001:8001"
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - LOAN_SUBMITTED_STREAM=${LOAN_SUBMITTED_STREAM:-loan_submitted}
      - LOAN_STATUS_STREAM=${LOAN_STATUS_STREAM:-loan_status}

  admin-dashboard:
    build: ./admin-dashboard
    container_name: admin-dashboard
    ports:
      - "8002:8000"
